In [1]:
import numpy as np

### Matrix Ordering

In [2]:
# Reordering of matricies
input_matrix = np.array([
    [2, 1, 3],
    [4, 3, 2],
    [1, 5, 2],
    [8, 3, 1]
])

# a matrix that allows me to order the matrix
matrix_order = np.argsort(input_matrix, axis=1)

ordered_matrix = np.array([input_matrix[i][matrix_order[i]] for i in range(input_matrix.shape[0])])
input_matrix = np.array([ordered_matrix[i][matrix_order[i]] for i in range(ordered_matrix.shape[0])])

ordered_matrix, input_matrix

(array([[1, 2, 3],
        [2, 3, 4],
        [1, 2, 5],
        [1, 3, 8]]),
 array([[2, 1, 3],
        [4, 3, 2],
        [1, 5, 2],
        [8, 3, 1]]))

In [3]:
# Reordering based on unqiue ids for matricies

ids = np.array([
    [4, 2, 3],
    [4, 5, 3],
    [4, 5, 2]
])

unique_ids = np.unique(ids)
# id_ordering = np.array([[2, 0, 1], [2, 3, 1], [2, 3, 0]])
id_to_order = {id_val: index for index, id_val in enumerate(unique_ids)}

id_ordering = np.vectorize(id_to_order.get)(ids)
id_ordering

array([[2, 0, 1],
       [2, 3, 1],
       [2, 3, 0]])

### Sort by row

In [4]:
# sort by first column, then second column
matrix = np.array([
    [1., 2],
    [0., 2],
    [0., 11],
    [0., 3],
    [1., 0],
    [1., 3]
])

transposed = matrix.T
sorted_indices = np.lexsort(transposed)
sorted_array = matrix[sorted_indices]
sorted_array

array([[ 1.,  0.],
       [ 0.,  2.],
       [ 1.,  2.],
       [ 0.,  3.],
       [ 1.,  3.],
       [ 0., 11.]])

In [5]:
# sort by first column, then second column; third column are the indices to track the change
lane_and_update_tuple = np.array([[ 0., 11.,  0.],
       [ 0.,  2.,  1.],
       [ 1.,  3.,  2.],
       [ 1., 11.,  3.],
       [ 0.,  3.,  4.],
       [ 1., 12.,  5.]])

sorted_indices = np.lexsort((lane_and_update_tuple[:, 1], lane_and_update_tuple[:, 0]))
sorted_array = lane_and_update_tuple[sorted_indices]
sorted_array

array([[ 0.,  2.,  1.],
       [ 0.,  3.,  4.],
       [ 0., 11.,  0.],
       [ 1.,  3.,  2.],
       [ 1., 11.,  3.],
       [ 1., 12.,  5.]])