In [1]:
import numpy as np

In [8]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
x_difference = 
a = np.array([10, 3, 4, 5, 7, 17, 15, 11]) # array with unique entries
# [1, 2, 3, 5, 7, 9, 10, 11]
b = a * ((np.sort(a) - a) >= 0).astype(int)
b

array([ 0,  2,  3,  5,  7,  0, 15, 11])

In [6]:
(np.sort(a) - a) < 0

array([ True, False, False, False, False,  True, False, False])

In [14]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_gaps = x[1:] - x[:-1]
x_gaps

array([1, 1, 2, 2, 1, 1, 2])

In [13]:
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
x_change[1:] - x_change[:-1]

array([-8,  0, -1,  0,  9, -3, -6])

In [22]:
# a = np.array([1,2,3,0,0,0,10,11,0,0,20])
# a = np.array([1,2,3,1,2,3,10,11,1,2,20])
a = np.array([1,2,3,1,2,3,10,11,1,2,20])
b = np.array([1,2,3,7,8,9,10,11,18,19,20])

In [19]:
mask = a != 0

increments = np.cumsum(mask) - np.cumsum(a != 0)

b = np.where(mask, a, a[mask][-1] + increments)
b

array([ 1,  2,  3, 20, 20, 20, 10, 11, 20, 20, 20])

In [23]:
np.cumsum(a)

array([ 1,  3,  6,  7,  9, 12, 22, 33, 34, 36, 56])

In [83]:
# Detected all places that have to be updated
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
# np.argsort(a), np.arange(a.shape[0])

val = a[-1]
b = np.copy(a)
b = val - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b
indices_to_change

array([ True, False, False, False, False,  True,  True, False])

In [82]:
important_indices = indices_to_change.astype(int)[]

(array([7, 6, 5, 4, 3, 2, 1, 0]), array([-1, -8, -7, -6, -4,  6,  4,  0]))

In [87]:
np.right_shift(indices_to_change.astype(int), 1), indices_to_change.astype(int)

(array([0, 0, 0, 0, 0, 0, 0, 0]), array([1, 0, 0, 0, 0, 1, 1, 0]))

In [109]:
a_int = np.copy(indices_to_change.astype(int))
important_indices = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_indices, a * important_indices

(array([0, 1, 0, 0, 0, 0, 0, 1]), array([ 0,  3,  0,  0,  0,  0,  0, 11]))

In [106]:
b_int = np.array([1, 0, 0, 0, 0, 1, 1, 0])
np.roll(b_int, 1)

array([0, 1, 0, 0, 0, 0, 1, 1])

In [75]:
indices_to_change = np.arange(a.shape[0])[::-1] > b
indices_to_change

array([ True,  True,  True,  True,  True, False, False, False])

In [30]:
a = np.array([0,0,0,0,0,0,10,0,0,0,20])
b = np.array([0,0,0,3,2,1,0,3,2,1,0])
c = np.array([10,10,10,10,10,10,10,20,20,20,20])
d = np.array([1,2,3,0,0,0,10,11,0,0,20])
mask_b = b >0
d += (c-b)*mask_b.astype(int)
d

array([ 1,  2,  3,  7,  8,  9, 10, 28, 18, 19, 20])

In [33]:
# a = np.array([0,0,0,0,0,0,10,0,0,0,20])
a = np.array([10,0,0,0,0,0,20,0,0,0,0])
c = np.array([10,10,10,10,10,10,10,20,20,20,20])
np.maximum.accumulate(a)

array([10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20])

In [112]:
# fill the 0 places with the highest value that is not part of the array
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([ 2,  3,  6,  7,  8,  9,  10, 11])

# count up (1, 2, 3, 4, ...) until 1, then start again from 1
c = np.array([0, 1, 0, 0, 0, 0, 1, 1])
d = np.array([1, 0, 1, 2, 3, 4, 0, 0])

In [117]:
np.arange(c.shape[0]) * np.roll(b_int, 1)

array([0, 1, 0, 0, 0, 0, 6, 7])

In [118]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
val = a[-1]
b = np.copy(a)
b = val - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
important_indices = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_indices, a * important_indices

(array([0, 1, 0, 0, 0, 0, 0, 1]), array([ 0,  3,  0,  0,  0,  0,  0, 11]))

In [119]:
np.arange(a.shape[0]) * important_indices

array([0, 1, 0, 0, 0, 0, 0, 7])