In [46]:
import numpy as np

In [129]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = a[-1] - b
k = np.arange(a.shape[0])[::-1] > b
c = np.where((np.roll(k.astype(int), 1) == 1) & (k.astype(int) == 0), 1, 0)
c

array([0, 1, 0, 0, 0, 0, 0, 1])

In [132]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
k = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(k.astype(int))
l = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
l

array([0, 1, 0, 0, 0, 0, 0, 1])

In [96]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
c = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_values = a * c

d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)
e = important_values
f = e[e.nonzero()].repeat(np.diff(np.append(np.where(e!=0),e.shape[0])))
g = np.roll(np.maximum.accumulate(np.argsort(e) * c), 1)
h = np.zeros_like(e)
h[g] = e
i = np.maximum.accumulate(h)
j = i - d
b, c, d, e, f, h, i, j

(array([ 1,  8,  7,  6,  4, -6, -4,  0]),
 array([0, 1, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 1, 2, 3, 4, 5, 0]),
 array([ 0,  3,  0,  0,  0,  0,  0, 11]),
 array([ 3,  3,  3,  3,  3,  3, 11]),
 array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]),
 array([ 2,  3, 10,  9,  8,  7,  6, 11]))

In [48]:
(np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)

array([1, 0, 1, 2, 3, 4, 5, 0])

In [100]:
d

array([1, 0, 1, 2, 3, 4, 5, 0])

In [97]:
(d>0).astype(int)

array([1, 0, 1, 1, 1, 1, 1, 0])

In [99]:
np.cumsum((d>0).astype(int))

array([1, 1, 2, 3, 4, 5, 6, 6])

In [102]:
(8-d) * (1-c)

array([7, 0, 7, 6, 5, 4, 3, 0])

In [51]:
a1 = e
b1 = np.roll(np.maximum.accumulate(np.argsort(a1) * c), 1)
# c1 = np.array([ 3,  0,  11,  0,  0,  0,  0, 0])
d1 = np.zeros_like(a1)
d1[b1] = a1
e1 = np.maximum.accumulate(d1)
d1, e1

(array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]))

In [52]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([7, 0, 2, 2, 2, 2, 2, 2])
c = np.array([ 3,  0,  11,  0,  0,  0,  0, 0])
d = np.zeros_like(a)
d[b] = a
e = np.maximum.accumulate(d)
d, e

(array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]))

In [53]:
# the array: np.array([10, 3, 4, 5, 7, 17, 15, 11])
# the position to be changed: np.array([1, 0, 0, 0, 0, 1, 1, 0])
# fill the 0 places with the highest value that is not part of the array
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([ 2,  3,  6,  7,  8,  9,  10, 11])

# count up (1, 2, 3, 4, ...) until 1, then start again from 1
c = np.array([0, 1, 0, 0, 0, 0, 1, 1])
# d = np.array([1, 0, 1, 2, 3, 4, 0, 0])
d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)

In [54]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11, 0, 0, 0, 13])
b = np.array([ 3,  0,  11,  0,  0,  0,  0, 0, 13, 0, 0, 0])
a, a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))

(array([ 0,  3,  0,  0,  0,  0,  0, 11,  0,  0,  0, 13]),
 array([ 3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13]))

In [55]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([0,  1,  0,  0,  0,  0,  0, 1])
a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))

array([ 3,  3,  3,  3,  3,  3, 11])

In [56]:
c = np.roll(np.maximum.accumulate(np.argsort(a) * b), 1)
c

array([7, 0, 2, 2, 2, 2, 2, 2])

In [57]:
np.argsort(a) * b

array([0, 2, 0, 0, 0, 0, 0, 7])

In [58]:
b[b.nonzero()].repeat(np.diff(np.append(np.where(b!=0),len(b))))

array([1, 1, 1, 1, 1, 1, 1])

In [59]:
np.maximum.accumulate(b)

array([0, 1, 1, 1, 1, 1, 1, 1])

In [60]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
# x_difference = 
a = np.array([10, 3, 4, 5, 7, 17, 15, 11]) # array with unique entries
# [1, 2, 3, 5, 7, 9, 10, 11]
b = a * ((np.sort(a) - a) >= 0).astype(int)
b

array([ 0,  3,  4,  5,  7,  0, 15, 11])

In [61]:
(np.sort(a) - a) < 0

array([ True, False, False, False, False,  True, False, False])

In [62]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_gaps = x[1:] - x[:-1]
x_gaps

array([1, 1, 2, 2, 1, 1, 2])

In [63]:
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
x_change[1:] - x_change[:-1]

array([-8,  0, -1,  0,  9, -3, -6])

In [64]:
# a = np.array([1,2,3,0,0,0,10,11,0,0,20])
# a = np.array([1,2,3,1,2,3,10,11,1,2,20])
a = np.array([1,2,3,1,2,3,10,11,1,2,20])
b = np.array([1,2,3,7,8,9,10,11,18,19,20])

In [65]:
mask = a != 0

increments = np.cumsum(mask) - np.cumsum(a != 0)

b = np.where(mask, a, a[mask][-1] + increments)
b

array([ 1,  2,  3,  1,  2,  3, 10, 11,  1,  2, 20])

In [66]:
np.cumsum(a)

array([ 1,  3,  6,  7,  9, 12, 22, 33, 34, 36, 56])

In [67]:
# Detected all places that have to be updated
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
# np.argsort(a), np.arange(a.shape[0])

val = a[-1]
b = np.copy(a)
b = val - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b
indices_to_change

array([ True, False, False, False, False,  True,  True, False])

In [68]:
# important_indices = indices_to_change.astype(int)[]

In [69]:
np.right_shift(indices_to_change.astype(int), 1), indices_to_change.astype(int)

(array([0, 0, 0, 0, 0, 0, 0, 0]), array([1, 0, 0, 0, 0, 1, 1, 0]))

In [70]:
a_int = np.copy(indices_to_change.astype(int))
important_indices = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_indices, a * important_indices

(array([0, 1, 0, 0, 0, 0, 0, 1]), array([ 0,  3,  0,  0,  0,  0,  0, 11]))

In [71]:
b_int = np.array([1, 0, 0, 0, 0, 1, 1, 0])
np.roll(b_int, 1)

array([0, 1, 0, 0, 0, 0, 1, 1])

In [72]:
indices_to_change = np.arange(a.shape[0])[::-1] > b
indices_to_change

array([ True, False, False, False, False,  True,  True, False])

In [73]:
a = np.array([0,0,0,0,0,0,10,0,0,0,20])
b = np.array([0,0,0,3,2,1,0,3,2,1,0])
c = np.array([10,10,10,10,10,10,10,20,20,20,20])
d = np.array([1,2,3,0,0,0,10,11,0,0,20])
mask_b = b >0
d += (c-b)*mask_b.astype(int)
d

array([ 1,  2,  3,  7,  8,  9, 10, 28, 18, 19, 20])

In [74]:
# a = np.array([0,0,0,0,0,0,10,0,0,0,20])
a = np.array([10,0,0,0,0,0,20,0,0,0,0])
c = np.array([10,10,10,10,10,10,10,20,20,20,20])
np.maximum.accumulate(a)

array([10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20])

In [75]:
# the array: np.array([10, 3, 4, 5, 7, 17, 15, 11])
# the position to be changed: np.array([1, 0, 0, 0, 0, 1, 1, 0])
# fill the 0 places with the highest value that is not part of the array
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([ 2,  3,  6,  7,  8,  9,  10, 11])

# count up (1, 2, 3, 4, ...) until 1, then start again from 1
c = np.array([0, 1, 0, 0, 0, 0, 1, 1])
# d = np.array([1, 0, 1, 2, 3, 4, 0, 0])
d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)

In [76]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11, 0, 0, 0, 13])
b = np.array([ 3,  0,  11,  0,  0,  0,  0, 0, 13, 0, 0, 0])
b, a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))

(array([ 3,  0, 11,  0,  0,  0,  0,  0, 13,  0,  0,  0]),
 array([ 3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13]))

In [77]:
np.maximum.accumulate(a)

array([ 0,  3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13])

In [78]:
a = np.array([ 0, 3, 0, 0, 0, 0, 0, 11, 0, 0, 0, 13])
b = np.array([ 3, 3, 11, 11, 11, 11, 11, 11, 13, 13, 13, 13])

In [79]:
import numpy as np

a = np.array([0, 3, 0, 0, 0, 0, 0, 11, 0, 0, 0, 13])
b = a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))
b

array([ 3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13])

In [80]:
np.arange(c.shape[0]) * np.roll(b_int, 1)

array([0, 1, 0, 0, 0, 0, 6, 7])

In [81]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
important_indices = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_indices, a * important_indices

(array([0, 1, 0, 0, 0, 0, 0, 1]), array([ 0,  3,  0,  0,  0,  0,  0, 11]))

In [82]:
arr = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
np.maximum.accumulate(arr), np.maximum.accumulate([ 3,  0,  11,  0,  0,  0,  0, ])

(array([ 0,  3,  3,  3,  3,  3,  3, 11]), array([ 3,  3, 11, 11, 11, 11, 11]))

In [83]:
arr = np.array([0, 3, 0, 0, 0, 0, 0, 11, 0, 0, 0, 5])
np.cumsum(arr)

array([ 0,  3,  3,  3,  3,  3,  3, 14, 14, 14, 14, 19])

In [84]:
important_indices

array([0, 1, 0, 0, 0, 0, 0, 1])

In [85]:
asd = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0])

In [86]:
np.cumsum(1 - asd)

array([ 1,  1,  2,  3,  4,  5,  6,  6,  7,  8,  8,  8,  9, 10, 11, 11, 12,
       13])

In [87]:
(np.arange(asd.shape[0]) + 1), np.cumsum(1 - asd)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18]),
 array([ 1,  1,  2,  3,  4,  5,  6,  6,  7,  8,  8,  8,  9, 10, 11, 11, 12,
        13]))

In [88]:
np.cumsum(1 - asd) * (1-asd)

array([ 1,  0,  2,  3,  4,  5,  6,  0,  7,  8,  0,  0,  9, 10, 11,  0, 12,
       13])

In [89]:
np.maximum.accumulate(asd * np.cumsum(1-asd))

array([ 0,  1,  1,  1,  1,  1,  1,  6,  6,  6,  8,  8,  8,  8,  8, 11, 11,
       11])

In [90]:
(np.cumsum(1 - asd) * (1-asd) - np.maximum.accumulate(asd * np.cumsum(1-asd))) * ( 1 - asd)

array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 0, 0, 1, 2, 3, 0, 1, 2])

In [153]:
a = np.array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0])
b = np.logical_and(b == 0, np.roll(b, 1) == 1).astype(int)
c = (np.arange(b.shape[0]) * b - 1) * b
f = c[c.nonzero()].repeat(np.diff(np.append(np.where(c!=0),c.shape[0])))
g = np.roll(np.maximum.accumulate(np.argsort(c) * b), 1)
# h[g] = c

# np.array([1, 0, 5, 4, 3, 2, 1, 0])
a,b,c,f,g,h

(array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([ 0,  0,  1,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0, 13,  0,  0,
         0,  0]),
 array([ 1,  1,  1,  1,  1,  1,  7,  7,  7,  7,  7,  7, 13, 13, 13, 13, 13]),
 array([15,  0,  0, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15]),
 array([0, 6, 0, 0, 0, 0, 0, 0]))

In [141]:
a,b,c,f,g

(array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0, 18]),
 array([18]),
 array([19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0]))

In [127]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = a[-1] - b
k = np.arange(a.shape[0])[::-1] > b
c = np.where((np.roll(k.astype(int), 1) == 1) & (k.astype(int) == 0), 1, 0)
c

array([0, 1, 0, 0, 0, 0, 0, 1])

In [147]:
a = np.array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5])
b = (a>0).astype(int)
a, b

(array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5]),
 array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1]))

In [151]:
b = np.array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1])
np.logical_and(b == 0, np.roll(b, 1) == 1).astype(int)

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])