In [1]:
import numpy as np

In [2]:
# a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
# b = a[-1] - b
# k = np.arange(a.shape[0])[::-1] > b
# c = np.where((np.roll(k.astype(int), 1) == 1) & (k.astype(int) == 0), 1, 0)
# c

In [3]:
def fill_zero_places(a):
    """
    a = np.array([0, 0, 0, 0,  3,  0,  0,  0,  0,  0, 11, 0, 0, 5, 0, 0, 17])
    b = np. array([ 0,  0,  0,  0,  0,  3,  3,  3,  3,  3,  3, 11, 11, 11,  5,  5,  5, 17])
    c = array([ 0,  0,  0,  0,  3,  3,  3,  3,  3,  3, 11, 11, 11,  5,  5,  5, 17])
    """
    a = np.append([-1], a)
    b = np.roll(a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),a.shape[0]))), 0)
    b[b<0] = 0
    c = b[1:]
    return c

a = np.array([0, 0, 0, 0,  3,  0,  0,  0,  0,  0, 11, 0, 0, 5, 0, 0, 17])
b = np.array([ 0,  1,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0, 0,  0,  0])

fill_zero_places(a), fill_zero_places(b)

(array([ 0,  0,  0,  0,  3,  3,  3,  3,  3,  3, 11, 11, 11,  5,  5,  5, 17]),
 array([ 0,  1,  1,  1,  1,  1,  1,  7,  7,  7,  7,  7,  7, 13, 13, 13, 13,
        13, 13, 13]))

In [4]:
def shift_values_to_next_available_zero(a):
    """
    a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
    b = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
    c = np.array([ 0,  1,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0, 0,  0,  0])
    d = np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0]),
    e = np.array([ 0,  0,  1,  1,  1,  1,  1,  1,  7,  7,  7,  7,  7,  7, 13, 13, 13, 13, 13, 13]
    f = np.array([2, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0]))
    """

    b = (a>0).astype(int)
    c = np.arange(b.shape[0]) * b
    c[-1] = -1 # acts as token
    d = np.roll(c[c.nonzero()].repeat(np.diff(np.append(np.where(c!=0),c.shape[0]))), 2)
    d = np.append(d, np.array([0])) * b
    c[-1] = 0
    d[d<0] = 0
    e = np.roll(fill_zero_places(c), 1)
    e[0] = 0
    f = np.zeros_like(a)
    np.add.at(f, e, a)
    f != 0

    return f

a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
shift_values_to_next_available_zero(a)

array([2, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0])

In [5]:
def fill_zero_values_ascending_rest_with_zero(a):
    """
    a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
    b = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
    c = np.array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0])
    """
    
    b = (a>0).astype(int)
    c = (np.cumsum(1 - b) * (1-b) - np.maximum.accumulate(b * np.cumsum(1-b))) * ( 1 - b)

    return c

a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
fill_zero_values_ascending_rest_with_zero(a)

array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0])

In [84]:
def find_zero_one_pattern(a):
    """
    a = np.array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
    b = np.array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
    """
    
    b = np.where((np.roll(a.astype(int), 1) == 1) & (a.astype(int) == 0), 1, 0)

    return b

a = np.array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
a, find_zero_one_pattern(a)

(array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]))

In [98]:
def find_one_zero_pattern(a):
    """
    a = np.array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
    b = np.array([-1,  1, -1,  1,  0,  0, -1,  1, -1,  0,  0,  0,  0,  1, -1,  0,  0, 0,  0,  1]
    c = np.array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
    """

    b = a - np.roll(a.astype(int), 1)
    c = b
    c[c<=0] = 0

    return c

a = np.array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
find_one_zero_pattern(a)

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [ ]:
def fill_zero_values_desscending_rest_with_zero(a):
    """
    a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
    b = np.array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0])
    c = np.array([1, 0, 5, 4, 3, 2, 1, 0, 5, 4, 3, 2, 1, 0, 5, 4, 3, 2, 1, 0])
    """
    
    b = fill_zero_values_ascending_rest_with_zero(a)
    c = (np.cumsum(1 - b) * (1-b) - np.maximum.accumulate(b * np.cumsum(1-b))) * ( 1 - b)

    return c

a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
fill_zero_values_ascending_rest_with_zero(a)

In [11]:
a = np.array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
z = find_zero_one_pattern(a)
b = np.where((np.roll(a.astype(int), 1) == 1) & (a.astype(int) == 0), 0, 1)
c = np.where((np.roll(a.astype(int), 1) == 0) & (a.astype(int) == 1), 0, 1)
# d = c = np.where((np.roll(a.astype(int), 0) == 0) & (a.astype(int) == 1), 0, 1)
# e = c = np.where((np.roll(a.astype(int), 0) == 1) & (a.astype(int) == 0), 1, 0)
x = np.array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

a, z, b, c, x, a | b
# a, z, b, c, d, e, x

(array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]),
 array([0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]))

array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0])

In [13]:
a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
b = (a>0).astype(int)
c = (np.cumsum(1 - b) * (1-b) - np.maximum.accumulate(b * np.cumsum(1-b))) * ( 1 - b)
a,b, c

(array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6]),
 array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0]))

In [14]:
a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
c = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_values = a * c

d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,
        3,  4,  5])

In [15]:
c = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1])
(np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)

array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 0, 1, 2, 0])

In [16]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
c = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_values = a * c

d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)
e = important_values
f = e[e.nonzero()].repeat(np.diff(np.append(np.where(e!=0),e.shape[0])))
g = np.roll(np.maximum.accumulate(np.argsort(e) * c), 1)
h = np.zeros_like(e)
h[g] = e
i = np.maximum.accumulate(h)
j = i - d
a, b, c, indices_to_change, d, e, f, g, h, i, j

(array([10,  3,  4,  5,  7, 17, 15, 11]),
 array([ 1,  8,  7,  6,  4, -6, -4,  0]),
 array([0, 1, 0, 0, 0, 0, 0, 1]),
 array([ True, False, False, False, False,  True,  True, False]),
 array([1, 0, 1, 2, 3, 4, 5, 0]),
 array([ 0,  3,  0,  0,  0,  0,  0, 11]),
 array([ 3,  3,  3,  3,  3,  3, 11]),
 array([7, 0, 2, 2, 2, 2, 2, 2]),
 array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]),
 array([ 2,  3, 10,  9,  8,  7,  6, 11]))

In [17]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
c = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_values = a * c

d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)
e = important_values
f = e[e.nonzero()].repeat(np.diff(np.append(np.where(e!=0),e.shape[0])))
g = np.roll(np.maximum.accumulate(np.argsort(e) * c), 1)
h = np.zeros_like(e)
h[g] = e
i = np.maximum.accumulate(h)
j = i - d
b, c, d, e, f, g, h, i, j

(array([ 1,  8,  7,  6,  4, -6, -4,  0]),
 array([0, 1, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 1, 2, 3, 4, 5, 0]),
 array([ 0,  3,  0,  0,  0,  0,  0, 11]),
 array([ 3,  3,  3,  3,  3,  3, 11]),
 array([7, 0, 2, 2, 2, 2, 2, 2]),
 array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]),
 array([ 2,  3, 10,  9,  8,  7,  6, 11]))

In [18]:
a = np.array([ 0,  1,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0, 0,  0,  0])
a = np.append([-1], a)
a = np.append(a, [-1])
b = np.roll(a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),a.shape[0]))), 0)
b[b<0] = 0
c = b[1:-1]
c

array([ 0,  1,  1,  1,  1,  1,  1,  7,  7,  7,  7,  7,  7, 13, 13, 13, 13,
       13, 13, 13])

In [19]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
k = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(k.astype(int))
l = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
l

array([0, 1, 0, 0, 0, 0, 0, 1])

In [20]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
c = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_values = a * c

d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)
e = important_values
f = e[e.nonzero()].repeat(np.diff(np.append(np.where(e!=0),e.shape[0])))
g = np.roll(np.maximum.accumulate(np.argsort(e) * c), 1)
h = np.zeros_like(e)
h[g] = e
i = np.maximum.accumulate(h)
j = i - d
b, c, d, e, f, g, h, i, j

(array([ 1,  8,  7,  6,  4, -6, -4,  0]),
 array([0, 1, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 1, 2, 3, 4, 5, 0]),
 array([ 0,  3,  0,  0,  0,  0,  0, 11]),
 array([ 3,  3,  3,  3,  3,  3, 11]),
 array([7, 0, 2, 2, 2, 2, 2, 2]),
 array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]),
 array([ 2,  3, 10,  9,  8,  7,  6, 11]))

In [21]:
(np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)

array([1, 0, 1, 2, 3, 4, 5, 0])

In [22]:
a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
b = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
q = np.arange(b.shape[0]) * b
q[-1] = -1 # acts as token
p = np.roll(q[q.nonzero()].repeat(np.diff(np.append(np.where(q!=0),q.shape[0]))), 2)
p = np.append(p, np.array([0])) * b
q[-1] = 0
p[p<0] = 0
r = np.zeros_like(q)
np.add.at(r, p, q)
r != 0
p, q, r

(array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0]),
 array([ 0,  1,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0,
         0,  0,  0]),
 array([ 1,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0]))

In [23]:
#      array([0, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,13, 0, 0, 0, 0, 0, 0])
a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6])
b = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
q = np.arange(b.shape[0]) * b
q[-1] = -1 # acts as token
p = np.roll(q[q.nonzero()].repeat(np.diff(np.append(np.where(q!=0),q.shape[0]))), 2)
p = np.append(p, np.array([0])) * b
q[-1] = 0
p[p<0] = 0
z = np.roll(fill_zero_places(q), 1)
z[0] = 0
r = np.zeros_like(a)
np.add.at(r, z, a)
r != 0
p, q, r

(array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0]),
 array([ 0,  1,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0,
         0,  0,  0]),
 array([2, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0]))

In [24]:
# q, np.roll(fill_zero_places(q), 1)
z = np.roll(fill_zero_places(q), 1)
z[0] = 0
z

array([ 0,  0,  1,  1,  1,  1,  1,  1,  7,  7,  7,  7,  7,  7, 13, 13, 13,
       13, 13, 13])

In [25]:
x = np.copy(q)
x
# np.roll(x[x.nonzero()].repeat(np.diff(np.append(np.where(x!=0),x.shape[0]))), 1)

array([ 0,  1,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0,
        0,  0,  0])

In [26]:
np.cumsum((d>0).astype(int))

array([1, 1, 2, 3, 4, 5, 6, 6])

In [27]:
(8-d) * (1-c)

array([7, 0, 7, 6, 5, 4, 3, 0])

In [28]:
a1 = e
b1 = np.roll(np.maximum.accumulate(np.argsort(a1) * c), 1)
# c1 = np.array([ 3,  0,  11,  0,  0,  0,  0, 0])
d1 = np.zeros_like(a1)
d1[b1] = a1
e1 = np.maximum.accumulate(d1)
d1, e1

(array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]))

In [29]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([7, 0, 2, 2, 2, 2, 2, 2])
c = np.array([ 3,  0,  11,  0,  0,  0,  0, 0])
d = np.zeros_like(a)
d[b] = a
e = np.maximum.accumulate(d)
d, e

(array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]))

In [30]:
# the array: np.array([10, 3, 4, 5, 7, 17, 15, 11])
# the position to be changed: np.array([1, 0, 0, 0, 0, 1, 1, 0])
# fill the 0 places with the highest value that is not part of the array
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([ 2,  3,  6,  7,  8,  9,  10, 11])

# count up (1, 2, 3, 4, ...) until 1, then start again from 1
c = np.array([0, 1, 0, 0, 0, 0, 1, 1])
# d = np.array([1, 0, 1, 2, 3, 4, 0, 0])
d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)

In [31]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11, 0, 0, 0, 13])
b = np.array([ 3,  0,  11,  0,  0,  0,  0, 0, 13, 0, 0, 0])
a, a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))

(array([ 0,  3,  0,  0,  0,  0,  0, 11,  0,  0,  0, 13]),
 array([ 3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13]))

In [32]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([0,  1,  0,  0,  0,  0,  0, 1])
a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))

array([ 3,  3,  3,  3,  3,  3, 11])

In [33]:
c = np.roll(np.maximum.accumulate(np.argsort(a) * b), 1)
c

array([7, 0, 2, 2, 2, 2, 2, 2])

In [34]:
np.argsort(a) * b

array([0, 2, 0, 0, 0, 0, 0, 7])

In [35]:
b[b.nonzero()].repeat(np.diff(np.append(np.where(b!=0),len(b))))

array([1, 1, 1, 1, 1, 1, 1])

In [36]:
np.maximum.accumulate(b)

array([0, 1, 1, 1, 1, 1, 1, 1])

In [37]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
# x_difference = 
a = np.array([10, 3, 4, 5, 7, 17, 15, 11]) # array with unique entries
# [1, 2, 3, 5, 7, 9, 10, 11]
b = a * ((np.sort(a) - a) >= 0).astype(int)
b

array([ 0,  3,  4,  5,  7,  0, 15, 11])

In [38]:
(np.sort(a) - a) < 0

array([ True, False, False, False, False,  True, False, False])

In [39]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_gaps = x[1:] - x[:-1]
x_gaps

array([1, 1, 2, 2, 1, 1, 2])

In [40]:
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
x_change[1:] - x_change[:-1]

array([-8,  0, -1,  0,  9, -3, -6])

In [41]:
# a = np.array([1,2,3,0,0,0,10,11,0,0,20])
# a = np.array([1,2,3,1,2,3,10,11,1,2,20])
a = np.array([1,2,3,1,2,3,10,11,1,2,20])
b = np.array([1,2,3,7,8,9,10,11,18,19,20])

In [42]:
mask = a != 0

increments = np.cumsum(mask) - np.cumsum(a != 0)

b = np.where(mask, a, a[mask][-1] + increments)
b

array([ 1,  2,  3,  1,  2,  3, 10, 11,  1,  2, 20])

In [43]:
np.cumsum(a)

array([ 1,  3,  6,  7,  9, 12, 22, 33, 34, 36, 56])

In [44]:
# Detected all places that have to be updated
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
# np.argsort(a), np.arange(a.shape[0])

val = a[-1]
b = np.copy(a)
b = val - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b
indices_to_change

array([ True, False, False, False, False,  True,  True, False])

In [45]:
# important_indices = indices_to_change.astype(int)[]

In [46]:
np.right_shift(indices_to_change.astype(int), 1), indices_to_change.astype(int)

(array([0, 0, 0, 0, 0, 0, 0, 0]), array([1, 0, 0, 0, 0, 1, 1, 0]))

In [47]:
a_int = np.copy(indices_to_change.astype(int))
important_indices = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_indices, a * important_indices

(array([0, 1, 0, 0, 0, 0, 0, 1]), array([ 0,  3,  0,  0,  0,  0,  0, 11]))

In [48]:
b_int = np.array([1, 0, 0, 0, 0, 1, 1, 0])
np.roll(b_int, 1)

array([0, 1, 0, 0, 0, 0, 1, 1])

In [49]:
indices_to_change = np.arange(a.shape[0])[::-1] > b
indices_to_change

array([ True, False, False, False, False,  True,  True, False])

In [50]:
a = np.array([0,0,0,0,0,0,10,0,0,0,20])
b = np.array([0,0,0,3,2,1,0,3,2,1,0])
c = np.array([10,10,10,10,10,10,10,20,20,20,20])
d = np.array([1,2,3,0,0,0,10,11,0,0,20])
mask_b = b >0
d += (c-b)*mask_b.astype(int)
d

array([ 1,  2,  3,  7,  8,  9, 10, 28, 18, 19, 20])

In [51]:
# a = np.array([0,0,0,0,0,0,10,0,0,0,20])
a = np.array([10,0,0,0,0,0,20,0,0,0,0])
c = np.array([10,10,10,10,10,10,10,20,20,20,20])
np.maximum.accumulate(a)

array([10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20])

In [52]:
# the array: np.array([10, 3, 4, 5, 7, 17, 15, 11])
# the position to be changed: np.array([1, 0, 0, 0, 0, 1, 1, 0])
# fill the 0 places with the highest value that is not part of the array
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
b = np.array([ 2,  3,  6,  7,  8,  9,  10, 11])

# count up (1, 2, 3, 4, ...) until 1, then start again from 1
c = np.array([0, 1, 0, 0, 0, 0, 1, 1])
# d = np.array([1, 0, 1, 2, 3, 4, 0, 0])
d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)

In [53]:
a = np.array([ 0,  3,  0,  0,  0,  0,  0, 11, 0, 0, 0, 13])
b = np.array([ 3,  0,  11,  0,  0,  0,  0, 0, 13, 0, 0, 0])
b, a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))

(array([ 3,  0, 11,  0,  0,  0,  0,  0, 13,  0,  0,  0]),
 array([ 3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13]))

In [54]:
np.maximum.accumulate(a)

array([ 0,  3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13])

In [55]:
a = np.array([ 0, 3, 0, 0, 0, 0, 0, 11, 0, 0, 0, 13])
b = np.array([ 3, 3, 11, 11, 11, 11, 11, 11, 13, 13, 13, 13])

In [56]:
import numpy as np

a = np.array([0, 3, 0, 0, 0, 0, 0, 11, 0, 0, 0, 13])
b = a[a.nonzero()].repeat(np.diff(np.append(np.where(a!=0),len(a))))
b

array([ 3,  3,  3,  3,  3,  3, 11, 11, 11, 11, 13])

In [57]:
np.arange(c.shape[0]) * np.roll(b_int, 1)

array([0, 1, 0, 0, 0, 0, 6, 7])

In [58]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
important_indices = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_indices, a * important_indices

(array([0, 1, 0, 0, 0, 0, 0, 1]), array([ 0,  3,  0,  0,  0,  0,  0, 11]))

In [59]:
arr = np.array([ 0,  3,  0,  0,  0,  0,  0, 11])
np.maximum.accumulate(arr), np.maximum.accumulate([ 3,  0,  11,  0,  0,  0,  0, ])

(array([ 0,  3,  3,  3,  3,  3,  3, 11]), array([ 3,  3, 11, 11, 11, 11, 11]))

In [60]:
arr = np.array([0, 3, 0, 0, 0, 0, 0, 11, 0, 0, 0, 5])
np.cumsum(arr)

array([ 0,  3,  3,  3,  3,  3,  3, 14, 14, 14, 14, 19])

In [61]:
important_indices

array([0, 1, 0, 0, 0, 0, 0, 1])

In [62]:
asd = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0])

In [63]:
k = asd
np.where((np.roll(k.astype(int), 1) == 1) & (k.astype(int) == 0), 1, 0)

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [64]:
np.cumsum(1 - asd)

array([ 1,  1,  2,  3,  4,  5,  6,  6,  7,  8,  8,  8,  9, 10, 11, 11, 12,
       13])

In [65]:
(np.arange(asd.shape[0]) + 1), np.cumsum(1 - asd)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18]),
 array([ 1,  1,  2,  3,  4,  5,  6,  6,  7,  8,  8,  8,  9, 10, 11, 11, 12,
        13]))

In [66]:
np.cumsum(1 - asd) * (1-asd)

array([ 1,  0,  2,  3,  4,  5,  6,  0,  7,  8,  0,  0,  9, 10, 11,  0, 12,
       13])

In [67]:
np.maximum.accumulate(asd * np.cumsum(1-asd))

array([ 0,  1,  1,  1,  1,  1,  1,  6,  6,  6,  8,  8,  8,  8,  8, 11, 11,
       11])

In [68]:
(np.cumsum(1 - asd) * (1-asd) - np.maximum.accumulate(asd * np.cumsum(1-asd))) * ( 1 - asd)

array([1, 0, 1, 2, 3, 4, 5, 0, 1, 2, 0, 0, 1, 2, 3, 0, 1, 2])

In [69]:
np.maximum.accumulate(asd * np.cumsum(1-asd))

array([ 0,  1,  1,  1,  1,  1,  1,  6,  6,  6,  8,  8,  8,  8,  8, 11, 11,
       11])

In [70]:
(np.roll(a, 1) + 1) * b

array([ 12,  88,  28,  30,  24, -48, -72,   0])

In [71]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = np.copy(a)
b = a[-1] - b
# a, b, np.arange(a.shape[0])[::-1]
indices_to_change = np.arange(a.shape[0])[::-1] > b

a_int = np.copy(indices_to_change.astype(int))
c = np.where((np.roll(a_int, 1) == 1) & (a_int == 0), 1, 0)
important_values = a * c

d = (np.cumsum(1 - c) * (1-c) - np.maximum.accumulate(c * np.cumsum(1-c))) * ( 1 - c)
e = important_values
f = e[e.nonzero()].repeat(np.diff(np.append(np.where(e!=0),e.shape[0])))
g = np.roll(np.maximum.accumulate(np.argsort(e) * c), 1)
h = np.zeros_like(e)
h[g] = e
i = np.maximum.accumulate(h)
j = i - d
b, c, d, e, f, g, h, i, j

(array([ 1,  8,  7,  6,  4, -6, -4,  0]),
 array([0, 1, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 1, 2, 3, 4, 5, 0]),
 array([ 0,  3,  0,  0,  0,  0,  0, 11]),
 array([ 3,  3,  3,  3,  3,  3, 11]),
 array([7, 0, 2, 2, 2, 2, 2, 2]),
 array([ 3,  0, 11,  0,  0,  0,  0,  0]),
 array([ 3,  3, 11, 11, 11, 11, 11, 11]),
 array([ 2,  3, 10,  9,  8,  7,  6, 11]))

In [72]:
a = np.array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0])
k = (a>0).astype(int)
# b = np.logical_and(b == 0, np.roll(b, 1) == 1).astype(int)
b = np.where((np.roll(k, 1) == 1) & (k == 0), 1, 0)
c = (np.roll(a, 1) + 1) * b
f = np.roll(c[c.nonzero()].repeat(np.diff(np.append(np.where(c!=0),c.shape[0]))), 1)
g = np.roll(np.maximum.accumulate(np.argsort(c) * b), 1)
h = np.zeros_like(c)
h[g] = c
a, b, c, f, g, h

(array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]),
 array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6]),
 array([6, 2, 2, 2, 2, 2, 2, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 4]),
 array([19,  0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
        17, 17, 17]),
 array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0]))

In [73]:
a = np.array([0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6]),
b = np.array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
q = np.arange(b.shape[0]) * b
q[-1] = -1 # acts as token
p = np.roll(q[q.nonzero()].repeat(np.diff(np.append(np.where(q!=0),q.shape[0]))), 2)
p = np.append(p, np.array([0])) * b
q[-1] = 0
p[p<0] = 0
r = np.zeros_like(q)
np.add.at(r, p, q)
r != 0
r

array([ 1,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0])

In [74]:
# r = np.zeros_like(q)
# r[p] = q
# r

# r = np.zeros_like(q, dtype=bool)
# np.logical_or.at(r, p, q)
# r = r.astype(q.dtype)
# r

r = np.zeros_like(q)
np.add.at(r, p, q)
r != 0
r

array([ 1,  7,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0])

In [75]:
c[c.nonzero()].repeat(np.diff(np.append(np.where(c!=0),c.shape[0])))

array([2, 2, 2, 2, 2, 2, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 4, 6])

In [76]:
a = np.array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0])
b = (a>0).astype(int)
b = np.logical_and(b == 0, np.roll(b, 1) == 1).astype(int)
c = (np.arange(b.shape[0]) * b - 1) * b
f = c[c.nonzero()].repeat(np.diff(np.append(np.where(c!=0),c.shape[0])))
g = np.roll(np.maximum.accumulate(np.argsort(c) * b), 1)
# h[g] = c

# np.array([1, 0, 5, 4, 3, 2, 1, 0])
a,b,c,f,g,h

(array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]),
 array([ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0, 12,  0,  0,  0,
         0,  0, 18]),
 array([ 6,  6,  6,  6,  6,  6, 12, 12, 12, 12, 12, 12, 18]),
 array([19,  0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
        17, 17, 17]),
 array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0]))

In [77]:
a,b,c,f,g

(array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]),
 array([ 0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0, 12,  0,  0,  0,
         0,  0, 18]),
 array([ 6,  6,  6,  6,  6,  6, 12, 12, 12, 12, 12, 12, 18]),
 array([19,  0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
        17, 17, 17]))

In [78]:
a = np.array([10, 3, 4, 5, 7, 17, 15, 11])
b = a[-1] - b
k = np.arange(a.shape[0])[::-1] > b
c = np.where((np.roll(k.astype(int), 1) == 1) & (k.astype(int) == 0), 1, 0)
c

ValueError: operands could not be broadcast together with shapes (8,) (20,) 

In [ ]:
a = np.array([1, 0, 1, 2, 3, 4, 5, 0, 0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5])
b = (a>0).astype(int)
a, b

In [ ]:
b = np.array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1])
np.logical_and(b == 0, np.roll(b, 1) == 1).astype(int)