In [1]:
import numpy as np

In [8]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
x_difference = 
a = np.array([10, 3, 4, 5, 7, 17, 15, 11]) # array with unique entries
# [1, 2, 3, 5, 7, 9, 10, 11]
b = a * ((np.sort(a) - a) >= 0).astype(int)
b

array([ 0,  2,  3,  5,  7,  0, 15, 11])

In [6]:
(np.sort(a) - a) < 0

array([ True, False, False, False, False,  True, False, False])

In [14]:
x = np.array([1, 2, 3, 5, 7, 8, 9, 11])
x_gaps = x[1:] - x[:-1]
x_gaps

array([1, 1, 2, 2, 1, 1, 2])

In [13]:
x_change = np.array([9, 1, 1, 0, 0, 9, 6, 0])
x_change[1:] - x_change[:-1]

array([-8,  0, -1,  0,  9, -3, -6])