### Imports and HTML-content

In [1]:
%run helper.py

In [2]:
from IPython.display import display, HTML
point_to_dist_angle = """

"""

In [3]:
from scipy.stats import multivariate_normal

def calc_likelihoods_for_distributions_and_points(matrix_dist, matrix_points):
    means = matrix_dist[:, 0]
    covariances = matrix_dist[:, 1:]
    likelihoods = np.array([multivariate_normal(mean=means[i], cov=covariances[i]).pdf(matrix_points) for i in range(len(means))])
    
    return likelihoods.T 

### Code

### Build Graph

In [4]:
@save_params
def create_graph_data(csv_file_name, iteration):
    classes_dict = {
        'goomba': 0,
        'mario': 1,
        'cloud': 2,
        'ground': 3,
        'bush': 4,
        'box': 5,
        'pipe': 6
    }
    
    class_names, boxes = get_classnames_boxes_from_csv(csv_file_name, iteration)
    num_nodes = len(boxes)
    edge_connections = cartesian_product_for_nodes(range(num_nodes))
    node_features = []
    matrix = np.empty((0, 2))
    normal_dist = [0, 0, 1, 0, 0, 1] # mu1, mu2, sig00, sig01, sig10, sig11
    dataset_number = int(csv_file_name.split('/')[-1].split('.')[0])

    if num_nodes == 1:
        box = boxes[0]
        width, height = abs(box['left'] - box['right']), abs(box['top'] - box['bottom'])
        # node_feature: (normal-distribution, class-label, x-val, y-val, width, height, dataset_number, iteration, id)
        node_features.append((*normal_dist, classes_dict[class_names[0]], box['center_x'], \
                              box['center_y'], width, height, dataset_number, iteration, 0))
        
        node_features = torch.tensor(node_features, dtype=torch.float)
        
        return Data(
            x=node_features,
            edge_index=torch.tensor([0]),
            edge_attr=torch.tensor([0])
        )
        
    for i, box in enumerate(boxes):
        new_row = np.array([[box['center_x'], box['center_y']]])
        matrix = np.vstack((matrix, new_row))

        width, height = abs(box['left'] - box['right']), abs(box['top'] - box['bottom'])
        # node_feature: (normal-distribution, class-label, x-val, y-val, width, height, dataset_number, iteration, id)
        node_features.append((*normal_dist, classes_dict[class_names[i]], box['center_x'], \
                              box['center_y'], width, height, dataset_number, iteration, i))
    
    dists, angles = dist_angle_from_matrix(matrix, edge_connections)
    
    node_features = torch.tensor(node_features, dtype=torch.float)
    edge_connections = torch.tensor(edge_connections)
    edges_features =  torch.tensor(np.stack((dists, angles), axis=-1))
    
    data = Data(
        x=node_features,
        edge_index=edge_connections.t().contiguous(),
        edge_attr=edges_features
    )

    return data

In [5]:
dataset = []
for i in range(4):
    csv_file_name = f"/workspaces/jupyterlite/content/pytroch-geometric/mario-tracking-data/{i:04d}.csv"
    df = pd.read_csv(csv_file_name)
    num_iterations = int(df.iloc[-1]['iteration']) # we start at index 1, so no need for `+ 1`
    
    for iteration in range(1, num_iterations):
        graph_data = create_graph_data(csv_file_name, iteration)
        dataset.append(graph_data)

train_dataset = dataset[:int(0.8 * len(dataset))]
test_dataset = dataset[int(0.8 * len(dataset)):]

train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1)

/workspaces/jupyterlite/content/pytroch-geometric/helper.py:73: RuntimeWarning: invalid value encountered in divide
  return np.linalg.norm(val_edge_pairs, axis=1), np.rad2deg(np.arctan(val_edge_pairs[:, 1] / val_edge_pairs[:, 0]))
/workspaces/jupyterlite/content/pytroch-geometric/helper.py:73: RuntimeWarning: divide by zero encountered in divide
  return np.linalg.norm(val_edge_pairs, axis=1), np.rad2deg(np.arctan(val_edge_pairs[:, 1] / val_edge_pairs[:, 0]))
/usr/local/lib/python3.8/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [6]:
int(csv_file_name.split('/')[-1].split('.')[0])

3

#### Message Passing

In [7]:
class SimpleGAT(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=1):
        super().__init__()
        self.conv1 = GATConv(in_channels, out_channels, heads=1, add_self_loops=False)

    def forward(self, x, edge_index, target_node):
        out = self.conv1(x, edge_index)

#### Loss

The Loss will be the SSE of the likelihoods that the points of frame i+1 belong to the distributions that were created from the graph on frame i.


In [8]:
def calc_point_indices_to_distributions(distributions, points, treshhold_likelihood = 0):
    if points.shape[0] == 0:
        return np.zeros(distributions.shape[0]) - 1
    
    if points.shape[0] == 1 and distributions.shape[0] == 1:
        likelihood_entries = calc_likelihoods_for_distributions_and_points(distributions, points)
    
        if likelihood_entries < treshhold_likelihood: return np.array([-1])
        return np.array([0])

    likelihoods = calc_likelihoods_for_distributions_and_points(distributions, points)
    sorted_indices = np.argsort(likelihoods, axis=0)
    ranks = np.zeros_like(likelihoods, dtype=int)
    n_rows, n_cols = likelihoods.shape
    ranks[sorted_indices, np.arange(n_cols)] = np.tile(np.arange(n_rows), (n_cols, 1)).T
    
    mask_binary = np.array((n_rows - ranks) <= n_cols, dtype=int)
    cumsum_array = np.cumsum(mask_binary, axis=0)
    
    s = min(n_rows, n_cols)
    extended_likelihood_entries = np.zeros((s+1, n_cols + 1))
    
    mask  = np.array((n_rows - ranks) <= n_cols)
    
    points_to_consider = np.where(np.any(mask, axis=1))[0]
    filtered_points = points[points_to_consider]
    
    likelihood_entries = calc_likelihoods_for_distributions_and_points(distributions, filtered_points)
    likelihood_indicies_to_filter = likelihood_entries < treshhold_likelihood
    # punish points that should be filtered out
    likelihood_entries[likelihood_indicies_to_filter] = 1e-50
    
    inv_percentage_of_likelihood = np.log(likelihood_entries)/ np.sum(np.log(likelihood_entries), axis=0)
    # percentage_of_likelihood = (1 / inv_percentage_of_likelihood) / np.sum( (1 / inv_percentage_of_likelihood), axis=0)
    # percentage_of_likelihood = inv_percentage_of_likelihood
    
    cost_matrix = np.log(inv_percentage_of_likelihood)
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
    
    max_index = max(col_ind) + 1
    points_to_distributions = np.zeros(max_index, dtype=row_ind.dtype) - 1
    
    points_to_distributions[col_ind] = row_ind

    # if punished points still come up ahead, set the association to -1
    for point_index, distribution_index in enumerate(col_ind):
        if likelihood_indicies_to_filter[point_index, distribution_index]:
            points_to_distributions[point_index] = -1
    
    return points_to_distributions

In [9]:
def classes_points_distributions_ids_from_graph(graph):
    graph = graph.x
    return graph[:, 6], graph[:, :6], graph[:, 7:9], graph[:, -1]

In [11]:
def indicies_of_filterted_array_entries(filtered_indicies, relative_indicies):
    return np.where(filtered_indicies)[0][relative_indicies]

In [17]:
def calculate_sse_for_distributions_and_points(graph_a, graph_b, mappings):
    node_attr_a = classes_points_distributions_ids_from_graph(graph_a)
    node_attr_b = classes_points_distributions_ids_from_graph(graph_b)
    
    dist_indicies = mappings[:, 0]
    distributions = node_attr_a[1][dist_indicies]
    distributions[:, :2] +=  np.array(node_attr_a[2][dist_indicies])[:]
    distributions = np.array(distributions.reshape(distributions.shape[0], -1, 2))
    
    points = node_attr_b[2][mappings[:, 1]]
    
    likelihoods = torch.tensor(calc_likelihoods_for_distributions_and_points(distributions, points))
    
    return torch.sum(likelihoods * mappings.unsqueeze(-1), dim=1)[0, :]

In [13]:
@save_params
def find_mapping_of_two_graphs(graph_a, graph_b):
    node_attributes_a = classes_points_distributions_ids_from_graph(graph_a)
    node_attributes_b = classes_points_distributions_ids_from_graph(graph_b)

    total_mappings = torch.empty((0, 2), dtype=torch.int)

    for label in classes_points_distributions_ids_from_graph(graph_b)[0].unique():
        dist_filter = (node_attributes_a[0] == label)
        dist_indicies = np.copy(dist_filter)
        points_filter = (node_attributes_b[0] == label)
        point_indicies = np.copy(points_filter)
        distributions = node_attributes_a[1][dist_indicies]
        distributions = np.array(distributions.reshape(distributions.shape[0], -1, 2))  # to have the correct format
        distributions[:, 0, :] += np.array(node_attributes_a[2][dist_indicies])
        points = node_attributes_b[2][point_indicies]
        num_dist_entries = torch.sum(dist_filter)
        
        mappings = torch.full((num_dist_entries, 2), -1, dtype=torch.int)
        mappings[:, 0] = torch.tensor((node_attributes_a[-1])[dist_filter], dtype=torch.int)
        
        dist_to_point_mapping = calc_point_indices_to_distributions(distributions, points)
        
        for i, dest_index in enumerate(dist_to_point_mapping):
            if dest_index == -1:
                continue
            relative_point_index = indicies_of_filterted_array_entries(points_filter, i)
            mappings[dest_index, 1] = torch.tensor((node_attributes_b[-1])[relative_point_index], dtype=torch.int)
        
        total_mappings = torch.cat((total_mappings, mappings), dim=0)

    return total_mappings

In [14]:
graph_a = train_dataset[700]
graph_b = train_dataset[700]

In [15]:
mappings = find_mapping_of_two_graphs(graph_a, graph_b)

/tmp/ipykernel_632536/3274530774.py:20: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mappings[:, 0] = torch.tensor((node_attributes_a[-1])[dist_filter], dtype=torch.int)
/tmp/ipykernel_632536/3274530774.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mappings[dest_index, 1] = torch.tensor((node_attributes_b[-1])[relative_point_index], dtype=torch.int)


In [16]:
mappings

tensor([[1, 1],
        [0, 0]], dtype=torch.int32)

In [18]:
calculate_sse_for_distributions_and_points(graph_a, graph_b, mappings)

array([[0.15915494, 0.        ],
       [0.        , 0.15915494]])

In [50]:
node_attr_a = classes_points_distributions_ids_from_graph(graph_a)
node_attr_b = classes_points_distributions_ids_from_graph(graph_b)

dist_indicies = mappings[:, 0]
distributions = node_attr_a[1][dist_indicies]
distributions[:, :2] +=  np.array(node_attr_a[2][dist_indicies])[:]
distributions = np.array(distributions.reshape(distributions.shape[0], -1, 2))

points = node_attr_b[2][mappings[:, 1]]

likelihoods = torch.tensor(calc_likelihoods_for_distributions_and_points(distributions, points))

In [22]:
distributions, points

(array([[[176.76 , 119.265],
         [  1.   ,   0.   ],
         [  0.   ,   1.   ]],
 
        [[151.585, 201.275],
         [  1.   ,   0.   ],
         [  0.   ,   1.   ]]], dtype=float32),
 tensor([[176.7600, 119.2650],
         [151.5850, 201.2750]]))

In [37]:
likelihoods

array([[0.15915494, 0.        ],
       [0.        , 0.15915494]])

In [36]:
likelihoods
# array([[0.15915494, 0.        ],
#       [0.        , 0.15915494]])

mappings
# tensor([[1, 1],
#        [0, 0]], dtype=torch.int32)

# result = [0.15915494, 0.15915494]

tensor([[1, 1],
        [0, 0]], dtype=torch.int32)

In [45]:
result = torch.tensor(likelihoods)[torch.arange(mappings.size(0)).unsqueeze(1), mappings]

# Flatten the result to get a 1D tensor
result = result.flatten()

In [41]:
likelihoods.gather(1, mappings)

AttributeError: 'numpy.ndarray' object has no attribute 'gather'

In [48]:
torch.sum(torch.tensor(likelihoods) * mappings, dim=0)

tensor([0.1592, 0.0000], dtype=torch.float64)

In [51]:
torch.sum(likelihoods * mappings.unsqueeze(-1), dim=0)

tensor([[0.1592, 0.0000],
        [0.0000, 0.1592]], dtype=torch.float64)

In [67]:
import torch

# Define the tensors
likelihoods = torch.tensor([[0.15915494, 0.0],
                            [0.0, 0.15915494]])

mappings = torch.tensor([[1, 0],
                         [0, 1]], dtype=torch.int32)

likelihoods[mappings[:, 0], ma]

SyntaxError: invalid syntax (1528378976.py, line 10)

In [60]:
likelihoods

tensor([[0.1592, 0.0000],
        [0.0000, 0.1592]])

In [61]:
for mapping in mappings:
    print(mapping)

tensor([1, 0], dtype=torch.int32)
tensor([0, 1], dtype=torch.int32)


In [63]:
a = torch.tensor([[0.15915494, 0.0],
                            [0.0, 0.15915494]])
b = torch.tensor([0, 1])
a[b[0], b[1]]

tensor(0.)